baseURL = "http://example.org/"
languageCode = "en-us"
paginate = 6
theme = "Nirva Wireless"
title = "Nirva Wireless"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About Us"
url = "#about"
weight = 2
[[menu.main]]
name = "Service"
url = "#service"
weight = 3
[[menu.main]]
name = "Research"
url = "#skills"
weight = 4
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 5

# Sitemap Menu
[[menu.sitemap]]
name = "Contact Us"
url = "contact"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright Â© Nirva Wireless 2023"
footerLogo = "images/contact/widget-logo.png"
# We're using formspree.io for form handling, paste your formspree url below

googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "3443 Tahoma Trl, College Station, TX 77845"
email = "nirvawireless@gmail.com"



 

# Social icons

[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 1

[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 2
